jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout zanadir-action repository
        uses: actions/checkout@v4
        
      - name: Check container directory contents (debug)
        uses: docker://mustachecase/zanadir:0.0.2
        with:
          args: ls -R /rules /storage
        
      - name: Run Zanadir Scan with Docker
        uses: docker://mustachecase/zanadir:0.0.2
        with:
          args: |
            scan
            --dir /github/workspace/${{ inputs.dir }}
            --excluded-categories ${{ inputs.excluded-categories }}
            --output ${{ inputs.output }}
            ${{ inputs.enforce == 'true' && '--enforce' || '' }}
            ${{ inputs.debug == 'true' && '--debug' || '' }}
