name: Zanadir Action
description: Scan your GitHub repository using Zanadir tool

inputs:
  dir:
    description: 'Path to the GitHub repository directory (required)'
    required: true
  excluded-categories:
    description: 'List of excluded categories (optional)'
    required: false
  enforce:
    description: 'Fails the CI process when at least one rule is met (optional)'
    required: false
  debug:
    description: 'Run the tool using debug mode (optional)'
    required: false
  output:
    description: 'Output format of the tool (Table, Json) (optional)'
    required: false

runs:
  using: "docker"
  image: "docker://mustachecase/zanadir:latest"
  args:
    - "scan"
    - "--dir"
    - "${{ inputs.dir }}"
    - "--excluded-categories"
    - "${{ inputs.excluded-categories }}"
    - "--output"
    - "${{ inputs.output }}"

    # Add --debug and --enforce only if they are true
    - ${{ if inputs.debug != 'false' }}:
      - "--debug"
    - ${{ if inputs.enforce != 'false' }}:
      - "--enforce"
