runs:
  using: "composite"
  steps:
    - run: |
        ARGS="scan --dir /repo"

        if [ -n "${{ inputs.excluded-categories }}" ]; then
          ARGS="$ARGS --excluded-categories '${{ inputs.excluded-categories }}'"
        fi

        if [ -n "${{ inputs.output }}" ]; then
          ARGS="$ARGS --output '${{ inputs.output }}'"
        fi

        if [ "${{ inputs.debug }}" = "true" ]; then
          ARGS="$ARGS --debug"
        fi

        if [ "${{ inputs.enforce }}" = "true" ]; then
          ARGS="$ARGS --enforce"
        fi

        docker run --rm \
          -v "${{ github.workspace }}:/repo" \
          -w /repo \
          mustachecase/zanadir:latest $ARGS
      shell: bash
