name: Zanadir Action
description: Scan your GitHub repository using Zanadir tool

inputs:
  dir:
    description: 'Path to the GitHub repository directory (required)'
    required: true
  excluded-categories:
    description: 'List of excluded categories (optional)'
    required: false
  enforce:
    description: 'Fails the CI process when at least one rule is met (optional)'
    required: false
  debug:
    description: 'Run the tool using debug mode (optional)'
    required: false
  output:
    description: 'Output format of the tool (Table, Json) (optional)'
    required: false

runs:
  using: "composite"
  steps:
    - name: Run Zanadir Scan
      shell: bash
      run: |
        cmd="zanadir scan --dir '${{ inputs.dir }}'"

        if [ -n "${{ inputs.excluded-categories }}" ]; then
          cmd="$cmd --excluded-categories '${{ inputs.excluded-categories }}'"
        fi

        if [ -n "${{ inputs.output }}" ]; then
          cmd="$cmd --output '${{ inputs.output }}'"
        fi

        if [ "${{ inputs.debug }}" = "true" ]; then
          cmd="$cmd --debug"
        fi

        if [ "${{ inputs.enforce }}" = "true" ]; then
          cmd="$cmd --enforce"
        fi

        echo "Running: $cmd"
        eval "$cmd"
